#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code
# Outputs OCCURRENCE_NUMBER IP HTTP_CODE ordered from highest to lowest

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn


