#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code
# Outputs OCCURRENCE_NUMBER IP HTTP_CODE ordered from highest to lowest

awk '
NF >= 9 && $1 ~ /^[0-9.]+$/ && $9 ~ /^[0-9]{3}$/ {
    count[$1 " " $9]++
}
END {
    for (key in count)
        printf "%d %s\n", count[key], key
}
' | sort -nr

