#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code and displays the number of occurrences

awk '
{
    count[$1 " " $9]++
}
END {
    for (k in count)
        printf "%d %s\n", count[k], k
}
' | sort -nr

