#!/usr/bin/env bash
# "bad luck from China" 4th iteration
# "bad luck from Japan" 9th iteration
# "bad luck from Italy" 17th iteration

count=1
while [ "$count" -le 20 ];
    do
    echo "$count"
    case "$count" in
4)
    echo "bad luck from China"
    ;;
9)
    echo "bad luck from Japan"
    ;;
17)
    echo "bad luck from Italy"
    ;;
    esac
    let count=count+1
done
